misitio/misitio/urls.py
from django.contrib import admin
from django.urls import path, include

#importamos la funcion de la clase persona
from persona.views import *


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('persona.urls'))
]

misitio/persona/urls.py
from django.urls import path
from persona.views import *

app_name = 'persona'

urlpatterns = [
    path('', index_persona, name='home'),
    path('crear', crearUsuario, name='crear'),
    path('borrar/<int:pk>', borrarUsuario, name='borrar'),
    path('lista', ver_lista_usuarios, name='ver_lista'),
    path('ver/<int:pk>', ver_detalle_usuario, name='ver_usuario'),
    path('listaedicion', vista_editar, name='actualizar'),
    path('editar/<int:pk>', fun_editar, name='editaru'),
    path('editarus/<int:pk>', editarUsuario, name='editarus'),
]

misitio/persona/models.py
from django.db import models

# Create your models here.


class Persona(models.Model):
    nombre = models.CharField(max_length=50, blank=False)
    apellido = models.CharField(max_length=50, blank=False)
    mail = models.EmailField(("Mail"), max_length=254)

misitio/persona/forms.py
from django import forms
from .models import Persona
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit

class PersonaForm(forms.Form):
    nombre = forms.CharField(max_length=50)
    apellido = forms.CharField(max_length=50)
    mail = forms.EmailField(max_length=100)
    

class PersonaModelForm(forms.ModelForm):
    class Meta:
        model = Persona
        fields = ['nombre', 'apellido', 'mail', 'id']

    def __init__(self, *args, **kwargs):
        super(PersonaModelForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_method = 'post'
        self.helper.add_input(Submit('submit', 'Guardar'))

misitio/persona/views.py
from django.shortcuts import render, redirect, redirect, get_object_or_404
from django.urls import reverse
from .models import Persona
from .forms import PersonaModelForm


# Create your views here.
def index_persona(request):
    return render(request, 'persona/home.html')

def crearUsuario(request):
    persona_lista = Persona.objects.all()

    form = PersonaModelForm()

    if(request.method == 'POST'):
        print("ha ingresado al metodo post ")

        form = PersonaModelForm(request.POST)
        if(form.is_valid()):
            form.save()
        else:
            print(form.errors)
    context = {
        'form': form,
        'persona_lista':persona_lista
    }
    return render(request, 'persona/crear.html', context)


def borrarUsuario(request, pk):
    Persona.objects.get(pk=pk).delete()

    persona_lista = Persona.objects.all()
    context = {
        'persona_lista':persona_lista
    }
    #return render(request, 'persona/crear.html')
    #return redirect(reverse('persona: borrar', kwargs = {'pk':pk}))
    #return index_persona(request)
    #return redirect(reverse('persona:crear', kwargs='pk':pk))
    return redirect('persona:crear')

    
def ver_lista_usuarios(request):
    persona_lista = Persona.objects.all()
    context = {
        'persona_lista':persona_lista
    }
    return render(request, 'persona/lista.html', context)


def ver_detalle_usuario(request, pk):
    persona = Persona.objects.get(pk=pk)

    context = {
        'persona':persona
    }
    return render(request, 'persona/detalle.html', context)



def vista_editar(request, pk=None):
    persona = Persona.objects.all()
    context = {
        'per_lista':persona
    }
    return render(request, 'persona/editar.html', context)


"""
def fun_editar(request, pk):
    persona = Persona.objects.get(pk = pk)

    form = PersonaModelForm(instance = persona)

    if(request.method == 'POST'):
        form = PersonaModelForm(request.POST, instance = persona)

        if(form.is_valid()):
            form.save()
        else:
            print(form.errors)
    context ={
        'form':form
    }
    return render(request, 'persona/modalmodificar.html', context)

"""

def fun_editar(request, pk=None):

    if(pk!=None):
        persona = Persona.objects.get(pk = pk)

        form = PersonaModelForm(instance = persona)

        if(request.method == 'POST'):
            form = PersonaModelForm(request.POST, instance = persona)

            if(form.is_valid()):
                form.save()
            else:
                print(form.errors)
            return render(request, 'persona/modal.html', {'form':form})
    context ={
        'form':form,
        'per':persona
    }
    return render(request, 'persona/modal.html', context)




def editarUsuario(request, pk):

    if(pk !=None):
        print(pk)

        persona = Persona.objects.get(pk = pk)

        print(pk)
        form = PersonaModelForm()

    if(request.method == 'POST'):
        print("ha ingresado al metodo post ")
        print(request)

        form = PersonaModelForm(request.POST, instance = persona)
        if(form.is_valid()):
            form.save()
        else:
            print(form.errors)

        persona_lista = Persona.objects.all()
    
    context = {
        'form': form,
        'persona_lista': persona_lista
    }
    
    return render(request, 'persona/lista.html', context)

misitio/persona/templates/persona/crear.html
{% extends 'index.html' %}
{% load static %}

 {% block main %}

    <section class="container">
        <div class="row">
            <div class="col-4">
            </div>
            <div class="col-4">
                <h2 id="lista">Nuevo usuario </h2>

                <div class="card">
                    <h5 class="card-header">Ingrese Datos</h5>
                    <div class="card-body">
                      <p class="card-text">
                        Complete los datos del nuevo Usuario
                      </p>
                        <p class="text-center">
                        <img src="{% static 'images/agregar.png' %}" width="20%">
                        </p>
                        
                      
                      <div id="liveAlertPlaceholder"></div>
                      
                      <div id="formulario">
                        <form method='post' name="formulario" onsubmit="return validar_campo(formulario)">
                        {% csrf_token %}
    
                        {{ form.as_p }}
    
                        <button type="submit" class="btn btn-outline-success" id="liveAlertBtn">Enviar</button>
                      </form>
                    </div>


                    </div>
                </div>


            </div>
            <div class="col-4">
            </div>
        </div>
    </section>

</br>
</br>
</br>

    <section class="container">
        <div class="row">
            <div class="col-2">
            </div>
            <div class="col-8">
                <h2 id="lista"> Lista de Usuarios </h2>
                <div class="card">
                    <h5 class="card-header">Usuarios</h5>
                    <div class="card-body">
                      <h5 class="card-title">Evaluación Q-Order Python - Django</h5>
                      <p class="card-text">
                        2- En una lista mostrar los usuarios creados
                      </p>
                    
                      <table class="table">
                        <thead>
                          <tr>
                            <th scope="col">Nombre</th>
                            <th scope="col">Apellido</th>
                            <th scope="col">Mail</th>
                            <th scope="col">Opciones</th>
                          </tr>
                        </thead>
                        <tbody class="table-group-divider">
    
                            {% for per in persona_lista %}
                          <tr>
                            <td>{{per.nombre}}</td>
                            <td> {{per.apellido}}</td>
                            <td> {{per.mail}}</td>
                            <td>
                                <a href="{% url 'persona:borrar' per.pk %}">
                                  <button type="button" class="btn btn-outline-warning">
                                    <img src="{% static 'images/eliminar.png' %}" width="20%">
                                    Borrar</button>
                                </a> <br>
                               
                            </td>
                          </tr>
    
                          {% endfor %}
    
                        </tbody>
                      </table>

                    </div>
                </div>



                
            </div>
            <div class="col-2">
            </div>
        </div>
    </section>



    {% endblock main %}

misitio/persona/templates/persona/detalle.html
{% extends 'index.html' %}
{% load static %}

 {% block main %}

 <section class="container">
    <div class="row">
        <div class="col-4">
        </div>
        <div class="col-4">

            <p class="text-center">
            <img src="{% static 'images/info.png' %}" width="20%">
            </p>

        </div>
        <div class="col-4">
        </div>
    </div>
</section>


    <section class="container">
        <div class="row">
            <div class="col-4">
            </div>
            <div class="col-4">
                <p class="text-center">

                <h2 id="lista"> Detalle del usuario: {{persona.nombre}}</h2>
                </p>
          
                <div id="info">
                <div class="card border-success mb-3" style="max-width: 18rem;">
                    <div class="card-header bg-transparent border-success">Nombre: {{persona.nombre}} </div>
                    <div class="card-body text-success">
                      <h5 class="card-title">Información</h5>
                      <p class="card-text">A continuación se detalla la información personal del usuario:{{persona.nombre}} .</p>
                      <ul class="list-group">
                        
                      
                        <li class="list-group-item list-group-item-primary"> <b> Nombre: </b> {{persona.nombre}}</li>
                        <li class="list-group-item list-group-item-secondary"><b>Apellido: </b>{{persona.apellido}}</li>
                        <li class="list-group-item list-group-item-success"><b>E-mail: </b> {{persona.mail}}</li>
                      </ul>
                     
                    </div>
                    <div class="card-footer bg-transparent border-success"> {{persona.nombre}} {{persona.apellido}} </div>
                    
                  </div>
                </div>
                <p class="text-center">
                    <a href="{% url 'persona:ver_lista' %}">
                <button type="button" class="btn btn-light">Volver</button>
                    </a>
            </p>

            </div>
            <div class="col-4">
            </div>
        </div>
    </section>


    {% endblock main %}

misitio/persona/templates/persona/editar.html
{% extends 'index.html' %}
{% load static %}

 {% block main %}

    <section class="container">
        <div class="row">
            <div class="col-2">
            </div>
            <div class="col-8">
                <h2 id="lista">
                <img src="{% static 'images/lista.png' %}" width="8%">   
                Lista de Usuarios 
              </h2>
                <div class="card">
                    <h5 class="card-header">Usuarios</h5>
                    <div class="card-body">
                      <h5 class="card-title">Lista de todos los usuarios creados</h5>
                      <p class="card-text">
                        <b>Ver detalle: </b>Para ver la información de un usuario en particular.
                      </p>
                    
                      <table class="table">
                        <thead>
                          <tr>
                            <th scope="col">Nombre</th>
                            <th scope="col">Apellido</th>
                            <th scope="col">Mail</th>
                            <th scope="col">Opciones</th>
                          </tr>
                        </thead>
                        <tbody class="table-group-divider">
    
                            {% for per in per_lista %}
                          <tr>
                            <td>{{per.nombre}}</td>
                            <td> {{per.apellido}}</td>
                            <td> {{per.mail}}</td>
                           
                            <td>
                          
                                  <button onclick="abrir_modal_edicion('{% url 'persona:editaru' per.pk%}')"  class="btn btn-outline-success">
                                  <img src="{% static 'images/editar.png' %}" width="20%"> Editar
                                  </button>
                        
                            </td>
                          </tr>
    
                          {% endfor %}
    
                        </tbody>
                      </table>

                    </div>
                </div>
            </div>
            <div class="col-2">
            </div>
        </div>
    </section>

    <div class="modal face" id="edicion" role="dialog">

    {% endblock main %}

misitio/persona/templates/persona/home.html
{% extends 'index.html'%}

{% load static %}

 {% block main %}
<section class="container">
    <div class="row">
        <div class="col-2">
        </div>
        <div class="col-6">
            <!-- Button trigger modal -->
                <button type="button" class="btn btn-info" data-bs-toggle="modal" data-bs-target="#staticBackdrop">
                    Ejercicio
                </button>

        </div>
        <div class="col-4">
        </div>
    </div>
</section>


<!-- Modal -->
<div class="modal fade modal-dialog-scrollable" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-scrollable">
      <div class="modal-content modal-dialog-scrollable">
        <div class="modal-header">
          <h5 class="modal-title" id="staticBackdropLabel">Ejercicio Práctico Q-Order</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body modal-dialog-scrollable">
            <h2>Práctica Django y Python</h2>

            <p>
                El mismo consiste en la implementación de los métodos CRUD para dar de alta, baja, modificar y listar usuarios.
            </p>

            <p>
                Para ello se debe crear el modelo de usuario con campos como Nombre, Apellido y Mail. Los campos Nombre y Apellido no deben admitir números por lo que se implementa Javascript para la validación de formularios.
            </p>

            <p>
                Se solicita la implementación de un navbar tipo menu y a la vez la herencia de estilos con bootstrap y hojas de estilo en cascada como css.
            </p>

            <p>
                Se solicita mayor aspecto estético y la implementación de un modal de bootstrap
            </p>

            <p class="text-center">
                <img src="{% static 'images/usuarios.png' %}" width="30%" class="rounded-circle bg-light">
            </p>

        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-success" data-bs-dismiss="modal">Cerrar</button>
        
        </div>
      </div>
    </div>
  </div>
  {% endblock main %}

misitio/persona/templates/persona/lista.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Creación de usuarios, alta usuarios mediante un formulario y luego una lista de usuarios">
    <meta name="keywords" content="usuarios django python alta ">
    <title>Q-Order Test</title>
    <link href="{% static 'bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  </head>
  <body>
    
    <section class="container">
        <div class="row">
            <div class="col-2">
               
            </div>
            <div class="col-8">
                <h1 id="titulo">Q-Order Test</h1>
            </div>
            <div class="col-2">
                
            </div>
        </div>
    </section>

    <section class="container">
        <div class="row">
            <div class="col-2">
               
            </div>
            <div class="col-8">
                <a href="{% url 'persona:crear' %}" style type="text/css" text-decoration: none>
                <button type="button" class="btn btn-success">Crear Usuarios</button>
                </a>
            </div>
            <div class="col-2">
                
            </div>
        </div>
    </section>




    <script src="{% static 'bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  </body>
</html>

misitio/persona/templates/persona/modal.html
{% load static %}
<link href="{% static 'bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
<link href="{% static 'bootstrap/css/style.css' %}" rel="stylesheet">


<div class="modal-dialog modal-lg" role="document" id="modal">

    <div class="modal-content">
    
        <div class="modal-header">
            <p class="text-start">
            <img src="{% static 'images/edicion.png' %}" width="15%">
            Complete los campos que desea editar
            </p>
        </div>

        <div class="modal-body">
        
            <div id="formodal">
                <form action="{% url 'persona:editarus' pk=per.pk %}" method='post' name="formulario" onsubmit="return  validar_campo(formulario)">
                    {% csrf_token %}

                    {{form.as_p}}
                    
                    <button type="submit" class="btn btn-outline-success" id="liveAlertBtn" >enviar</button>
                    
                </form>
        
            </div>


        </div>

        <div class="modal-footer">
            <div id="liveAlertPlaceholder"></div>
        </div>
    </div>

</div>

<script src="http://code.jquery.com/jquery-1.11.0.min.js"></script>
<script src="{% static 'bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'bootstrap/js/validation.js' %}"></script>

misitio/persona/templates/persona/modalmodificar.html
{% extends 'index.html' %}
{% load static %}

 {% block main %}

    <section class="container">
        <div class="row">
            <div class="col-4">
            </div>
            <div class="col-4">
                <h2 id="lista">Nuevo usuario </h2>

                <div class="card">
                    <h5 class="card-header">Ingrese Datos</h5>
                    <div class="card-body">
                      <p class="card-text">
                        Complete los datos del nuevo Usuario
                      </p>
                        <p class="text-center">
                        <img src="{% static 'images/agregar.png' %}" width="20%">
                        </p>
                        
                      
                      <div id="liveAlertPlaceholder"></div>
                      <div id="formulario">
                        <form action="{% url 'persona:editarus' object.id %}" method='post' name="formulario" onsubmit="return validar_campo(formulario)">
                        {% csrf_token %}
    
                        {{ form.as_p }}
    
                        <button type="submit" class="btn btn-light">Enviar</button>
                      </form>
                    </div>


                    </div>
                </div>


            </div>
            <div class="col-4">
            </div>
        </div>
    </section>

</br>
</br>
</br>

  


    {% endblock main %}

misitio/persona/templates/persona/modificar.html
{% extends 'index.html' %}
{% load static %}

 {% block main %}
    <section class="container">
        <div class="row">
            <div class="col-2">
            </div>
            <div class="col-8">
                <h2> Lista de Usuarios </h2>
                <div class="card">
                    <h5 class="card-header">Usuarios</h5>
                    <div class="card-body">
                      <h5 class="card-title">Evaluación Q-Order Python - Django</h5>
                      <p class="card-text">
                        2- En una lista mostrar los usuarios creados
                      </p>
                    
                      <table class="table">
                        <thead>
                          <tr>
                            <th scope="col">Nombre</th>
                            <th scope="col">Apellido</th>
                            <th scope="col">Mail</th>
                            <th scope="col">Opciones</th>
                          </tr>
                        </thead>
                        <tbody class="table-group-divider">
    
                            {% for per in persona_lista %}
                          <tr>
                            <td>{{per.nombre}}</td>
                            <td> {{per.apellido}}</td>
                            <td> {{per.mail}}</td>
                            <td>
                              
                                <button onclick="abrir_modal_edicion('{% url 'persona:actualizar' per.pk %}');" class="btn btn-primary">
                                    editar
                                  </button>
                                </a>
                                  
                            </td>
                          </tr>
    
                          {% endfor %}
    
                        </tbody>
                      </table>

                    </div>
                </div>



                
            </div>
            <div class="col-2">
            </div>
        </div>
    </section>


    <div class="modal fade" id="edicion" role="dialog">

    </div>



    {% endblock main %}

misitio/templates/index.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Creación de usuarios, alta usuarios mediante un formulario y luego una lista de usuarios">
    <meta name="keywords" content="usuarios django python alta ">
    <title>Q-Order Test</title>
    <link href="{% static 'bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'bootstrap/css/style.css' %}" rel="stylesheet">

    {% block extra_css %}{% endblock extra_css %}

  </head>
  <body>

   <section id="cuerpo">
    
    <section class="container">
        <div class="row">
            <div class="col-2" id="titulo">
               
            </div>
            <div class="col-8" id="titulo">
                <h1 id="titulo">Q-Order Test</h1>
            </div>
            <div class="col-2" id="titulo">

                <img src="{% static 'images/usuarios.png' %}" width="30%">
                <br>
                <p>Gestión de Usuarios</p>
            </div>
        </div>
    </section>

    <section class="container">
        <div class="row">
            <div class="col-2" id="nav">
               
            </div>
            <div class="col-8" id="nav">
                <div id="navegacion">
                  <ul class="nav nav-pills nav-fill">
                    <li class="nav-item">
                        <a href="{% url 'persona:home' %}" style type="text/css" text-decoration: none>
                            <button class="btn btn-outline-success me-2" type="button">Home</button>
                        </a>

                    </li>
                    <li class="nav-item">
                        <a href="{% url 'persona:actualizar' %}" style type="text/css" text-decoration: none>
                            <button class="btn btn-outline-success me-2" type="button">Editar Usuarios</button>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'persona:ver_lista' %}" style type="text/css" text-decoration: none>
                            <button class="btn btn-outline-success me-2" type="button">Ver Lista de Usuarios</button>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'persona:crear' %}" style type="text/css" text-decoration: none>
                            <button class="btn btn-outline-success me-2" type="button">Crear Usuarios</button>
                        </a>
                    </li>
                  </ul>
                </div>
                
            </div>
            <div class="col-2" id="nav">
                
            </div>
        </div>
    </section>

    {% block main %}

    {% endblock main %}


    <script src="http://code.jquery.com/jquery-1.11.0.min.js"></script>
    <script src="{% static 'bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'bootstrap/js/validation.js' %}"></script>
    {% block extra_js %}{% endblock extra_js %}
</section>
  </body>
</html>